kind: Deployment
apiVersion: apps/v1
metadata:
  name: quality-frontend-dashboard
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app: quality-dashboard
    app.kubernetes.io/component: quality-frontend
    app.kubernetes.io/instance: quality-dashboard
    app.kubernetes.io/name: quality-dashboard
    component: quality-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quality-dashboard
      component: quality-frontend
  template:
    metadata:
      labels:
        app: quality-dashboard
        app.kubernetes.io/component: quality-frontend
        app.kubernetes.io/instance: quality-dashboard
        app.kubernetes.io/name: quality-dashboard
        component: quality-frontend
    spec:
      serviceAccountName: dashboard-proxy
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      containers:
        - name: quality-frontend-dashboard
          env:
            - name: REACT_APP_API_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: quality-dashboard-configmap
                  key: BACKEND_ROUTE
            - name: FRONTEND_REDIRECT_URI
              valueFrom:
                configMapKeyRef:
                  name: quality-dashboard-configmap
                  key: FRONTEND_REDIRECT_URI
            - name: DEX_ISSUER
              valueFrom:
                secretKeyRef:
                  name: quality-dashboard-secrets-c5984t4th2
                  key: dex-issuer
            - name: DEX_APPLICATION_ID
              valueFrom:
                secretKeyRef:
                  name: quality-dashboard-secrets-c5984t4th2
                  key: dex-application-id
          ports:
            - name: http
              containerPort: 9000
              protocol: TCP
          imagePullPolicy: Always
          image: >-
            quay.io/flacatus/qs-frontend:latest
